# Generated by Django 3.0.6 on 2020-05-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodintake',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
