# Generated by Django 3.0.6 on 2020-06-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_foodintake_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
