# Generated by Django 3.0.6 on 2020-06-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200603_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodintake',
            old_name='food_id',
            new_name='food',
        ),
    ]
