# Generated by Django 3.0.6 on 2020-06-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200603_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodintake',
            old_name='food',
            new_name='food_id',
        ),
    ]
