# Generated by Django 3.0.6 on 2020-06-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200603_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodintake',
            old_name='food_id',
            new_name='food_id_a',
        ),
    ]
