# Generated by Django 3.0.6 on 2020-06-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200603_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodintake',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
