# Generated by Django 3.0.6 on 2020-06-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20200603_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodintake',
            name='food_id',
            field=models.IntegerField(),
        ),
    ]
