# Generated by Django 3.0.6 on 2020-06-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20200603_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodintake',
            name='food_id',
        ),
    ]
