# Generated by Django 3.0.6 on 2020-06-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_remove_foodintake_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodintake',
            name='food_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodintake',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
